on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 1 executed!"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 2 executed!"    
  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 3 executed!"  
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test
      - run: npm run build             